#kibana installation:
#===================

- hosts: localhost
  tasks:
  - name: Install Kibana with apt
    yum:
     name: https://artifacts.elastic.co/downloads/kibana/kibana-7.9.3-x86_64.rpm
     state: present

  # Configurations

  - name: Updating the config file to allow outside access
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'server.host:'
      line: 'server.host: 0.0.0.0'

  - name: Defining server port
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'server.port:'
      line: 'server.port: 5601'

  - name: Defining Elasticsearch URL
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'elasticsearch.url:'
      line: 'elasticsearch.url: "http://localhost:9200"'

  # Starting Kibana

  - name: Starting Kibana
    service:
      name: kibana
      state: started


